version: "2"
services:
    php-apache:
        image: domainadd
        build: .
        hostname: domainadd
        ports:
            - 8080:80
        env_file: 
            - .env
        volumes:
            - ./src/:/var/www/html
